module.exports = {
  url: 'https://julianolima.github.io/',
  pathPrefix: '/',
  title: 'Blog by Juliano Lima',
  subtitle: 'Engenheiro de software, cientista da computação, sommelier de desenhos e comentarista amador de futebol.',
  copyright: '© All rights reserved.',
  disqusShortname: '',
  postsPerPage: 4,
  googleAnalyticsId: 'UA-177351255-1',
  useKatex: false,
  menu: [
    {
      label: 'Artigos',
      path: '/',
    },
    {
      label: 'Sobre mim',
      path: '/pages/about',
    },
    {
      label: 'Contato',
      path: '/pages/contacts',
    },
  ],
  author: {
    name: 'Juliano Lima',
    photo: '/photo.png',
    bio: 'Engenheiro de software, cientista da computação, sommelier de desenhos e comentarista amador de futebol.',
    contacts: {
      email: '',
      facebook: 'juliano.gutierrez.92',
      telegram: 'julianogt',
      twitter: 'julianodgtz',
      github: 'JulianoGTZ',
      rss: '',
      vkontakte: '',
      linkedin: 'julianopereiralima',
      instagram: 'julianogt',
      line: '',
      gitlab: '',
      weibo: '',
      codepen: '',
      youtube: '',
      soundcloud: '',
    },
  },
};
